FROM python:3.5-slim

RUN apt-get update
RUN apt-get install -y libglib2.0-0
RUN apt-get install -y libsm6 libxext6 libxrender-dev
RUN apt-get install -y protobuf-compiler python-pil python-lxml

WORKDIR /app

COPY . /app

RUN pip install --trusted-host pypi.python.org -r requirement.txt

RUN protoc object_detection/protos/*.proto --python_out=.
RUN export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim
RUN export QT_X11_NO_MITSHM=1

CMD ["python", "app.py"]